server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha

spring:
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configtree:/run/secrets/}

coordinator:
  api:
    admin-password: ${REDIS_STREAM_COORDINATOR_ADMIN_PASSWORD:password}
  coordination:
    state-mutex:
      ttl-ms: 30000
      acquire-timeout-ms: 5000
      retry-interval-ms: 100
