PROTOCOL_VERSION = 1
DEFAULT_HEARTBEAT_INTERVAL_SECONDS = 3.0
DEFAULT_POLL_TIMEOUT_SECONDS = 0.25
DEFAULT_REBALANCE_TIMEOUT_SECONDS = 60.0
DEFAULT_ROUTING_REFRESH_SECONDS = 5.0
DEFAULT_PUBLISH_MAX_ATTEMPTS = 2
DEFAULT_XADD_MAX_LEN = 100_000


OK = "OK"
RETRY = "RETRY"
SYNC_METADATA = "SYNC_METADATA"
REVOKE_PENDING = "REVOKE_PENDING"
UNKNOWN_MEMBER_ID = "UNKNOWN_MEMBER_ID"
FENCED_MEMBER_EPOCH = "FENCED_MEMBER_EPOCH"
UNSUPPORTED_PROTOCOL = "UNSUPPORTED_PROTOCOL"
INVALID_REQUEST = "INVALID_REQUEST"

