server:
  port: ${SERVER_PORT:18081}

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha

spring:
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configtree:/run/secrets/}
  application:
    name: redisstream-consumer-pod-sample
  data:
    redis:
      cluster:
        nodes:
          - ${REDIS_CLUSTER_NODE_1:localhost:7001}
          - ${REDIS_CLUSTER_NODE_2:localhost:7002}
          - ${REDIS_CLUSTER_NODE_3:localhost:7003}

redis-stream-coordinator:
  coordinator-base-url: ${COORDINATOR_BASE_URL:http://localhost:8080}
  username: ${COORDINATOR_USERNAME:}
  password: ${COORDINATOR_PASSWORD:}
