server:
  port: ${SERVER_PORT:18090}

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha

spring:
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configtree:/run/secrets/}
  application:
    name: redisstream-publisher-pod-sample
  data:
    redis:
      cluster:
        nodes:
          - ${REDIS_CLUSTER_NODE_1:localhost:7001}
          - ${REDIS_CLUSTER_NODE_2:localhost:7002}
          - ${REDIS_CLUSTER_NODE_3:localhost:7003}

redis-stream-coordinator:
  coordinator-base-url: ${COORDINATOR_BASE_URL:http://localhost:8080}

sample:
  publisher:
    auto-publish-enabled: ${PUBLISHER_AUTO_PUBLISH_ENABLED:true}
    publish-interval-ms: ${PUBLISHER_PUBLISH_INTERVAL_MS:1000}
    partition-key-prefix: ${PUBLISHER_PARTITION_KEY_PREFIX:order}
    payload-prefix: ${PUBLISHER_PAYLOAD_PREFIX:sample-message}
